import{a as f,S as m,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const p="https://pixabay.com/api/",g="52557115-ad1d170ba64bf9f0fce8182bd";async function h(o,s=40){const e={key:g,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s};try{return(await f.get(p,{params:e})).data}catch(a){throw a}}const d=document.querySelector(".gallery"),y=new m(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){const s=o.map(e=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>`).join("");d.insertAdjacentHTML("beforeend",s),y.refresh()}function L(){d.innerHTML=""}const i=document.getElementById("loader");function w(){i&&(i.classList.remove("hidden"),i.classList.add("visible"))}function c(){i&&(i.classList.remove("visible"),i.classList.add("hidden"))}const u=document.querySelector(".form"),v=u.elements["search-text"],E=40;u.addEventListener("submit",async o=>{o.preventDefault();const s=v.value.trim();if(!s){n.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}L(),w();try{const e=await h(s,E);if(!e||!Array.isArray(e.hits)||e.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c();return}b(e.hits),n.success({title:"Success",message:`Found ${e.totalHits} images. Showing ${e.hits.length}.`,position:"topRight",timeout:2e3})}catch(e){console.error(e),n.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{c()}});
//# sourceMappingURL=index.js.map
